### PR TITLE
fix/fact-check-form

### LINKED ISSUE #528: cant create claim in fact check form

### PR DESCRIPTION
**Pull request by vsumit89**
made footer null in the create claim modal in factcheck form.

### CODE REVIEW

File: studio/src/pages/fact-checks/components/FactCheckForm.js [hunk 1]
```diff
@@ -218,7 +218,13 @@ function FactCheckForm({ onCreate, data = {}, actions = {}, format }) {
         message="You have unsaved changes, are you sure you want to leave?"
       />
       {visible && (
-        <Modal visible={visible} onOk={handleOk} onCancel={handleCancel} maskClosable={false}>
+        <Modal 
+          visible={visible} 
+          onOk={handleOk} 
+          onCancel={handleCancel}
```
Comment (shreeharsha-factly) [inline studio/src/pages/fact-checks/components/FactCheckForm.js]: @vsumit89 Does `onOk` and `onCancel` handlers are required?

Comment (vsumit89) [reply studio/src/pages/fact-checks/components/FactCheckForm.js]: onCancel is required. I removed onOk.
